import bcrypt from 'bcryptjs'

const data = {

  products: [
    {
      name: 'Gourde Supreme',
      slug: 'Gourde',
      category: 'Gourde',
      image: '/images/gourde-blanche.jpg',
      price: 4000,
      brand: 'Supreme',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Magnifique Gourde',
      isFeatured: true,
      banner: '/images/gourde-blanche.jpg',
    },
    {
      name: 'Gourde Panda',
      slug: 'Gourde',
      category: 'Gourde',
      image: '/images/gourde-blanche2.jpg',
      price: 4000,
      brand: 'Panda',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Magnifique Gourde',
      isFeatured: true,
      banner: '/images/gourde-blanche2.jpg',
    },
    {
      name: 'gourde Myprotein',
      slug: 'gourde',
      category: 'gourde',
      image: '/images/gourde-blanche3.jpg',
      price: 3500,
      brand: 'Myprotein',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Magnifique Gourde',
    },
    {
      name: 'gourde-noir',
      slug: 'gourde',
      category: 'gourde',
      image: '/images/gourde-noir1.jpg',
      price: 4000,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Magnifique Gourde',
    },
    {
      name: 'gourde-noir',
      slug: 'gourde',
      category: 'gourde',
      image: '/images/gourde-noir2.jpg',
      price: 4000,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Magnifique Gourde pratique',
    },
    {
      name: 'gourde-noir',
      slug: 'gourde',
      category: 'gourde',
      image: '/images/gourde-noir3.jpg',
      price: 3500,
      brand: 'Jordan',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Magnifique Gourde tres populaire',
    },
  ],
}

export default data
